worker_processes auto;
pid /tmp/umbod/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    client_body_temp_path /tmp/umbod/client_temp;
    proxy_temp_path /tmp/umbod/proxy_temp;
    fastcgi_temp_path /tmp/umbod/fastcgi_temp;
    uwsgi_temp_path /tmp/umbod/uwsgi_temp;
    scgi_temp_path /tmp/umbod/scgi_temp;
    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        '' $scheme;
    }
    map $http_x_forwarded_host $forwarded_host {
        default $http_x_forwarded_host;
        '' $http_host;
    }
    include /tmp/umbod/default.conf;
}
