<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting><AssemblyName>Umbod.Windows</AssemblyName><RootNamespace>Umbod.Windows</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../Umbod.Core/Umbod.Core.csproj" /></ItemGroup></Project>
